#!/bin/sh

set -eu

cd "$(git rev-parse --show-toplevel)"

echo "Running cargo fmt..."
cargo fmt --all -- --check

echo "Running cargo check..."
cargo check --all-targets

echo "Running cargo tests..."
cargo test --all-targets
